# Generated by Django 3.1.3 on 2020-11-26 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0002_auto_20201126_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='Email',
            field=models.EmailField(default='khosravani_hossein@yahoo.com', max_length=255),
        ),
        migrations.AlterField(
            model_name='expense',
            name='text',
            field=models.CharField(max_length=255, verbose_name='Comments:'),
        ),
        migrations.AlterField(
            model_name='income',
            name='text',
            field=models.CharField(max_length=255, verbose_name='Comments:'),
        ),
    ]
