# Generated by Django 3.1.3 on 2020-11-26 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0004_income_deuration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='Email',
            field=models.EmailField(default='Enter your Email...', max_length=255),
        ),
        migrations.AlterField(
            model_name='income',
            name='deuration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
