# Generated by Django 3.1.3 on 2020-11-27 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0005_auto_20201126_1958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='Email',
        ),
        migrations.RemoveField(
            model_name='income',
            name='deuration',
        ),
    ]
